name: build

on:
  push:
    branches:
      - "**"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: Run CodeBuild
      uses: aws-actions/aws-codebuild-run-build@v1.0.3
      with:
        project-name: aws-codebuild-run-build-sandbox
        buildspec-override: buildspecs/run-build.yaml
# /codebuild/output/src613505839/src/github.com/odan-sandbox/buildspecs/run-build.yaml

#pwd:  /codebuild/output/src889538216/src/github.com/odan-sandbox/aws-codebuild-run-build-sandbox